/**
 * Seeds one fully-completed application so the demo screens have data.
 *
 *   npm run seed        (runs the whole chain — this one goes last)
 *   npm run seed:demo   (this script only)
 *
 * Without it, several screens are technically correct but visibly empty:
 * My Applications, the "Resume sent" viewer, the monthly placement chart, top
 * companies, highest package, and the placement rate. All of those need a
 * single application that has reached Placed with a CTC on the offer.
 *
 * Safe to re-run. The application is matched on the unique
 * {applicantID.user, jobId} pair the schema already enforces and updated in
 * place, and an existing resume file is reused rather than uploaded again, so
 * re-seeding never duplicates a record or orphans a GridFS file.
 *
 * Depends on seed.js (for the student and recruiter) and seedJobs.js (for the
 * posting), so run those first.
 */
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import mongoose from "mongoose";
import { config } from "dotenv";

import { Application } from "./models/applicationSchema.js";
import { Job } from "./models/jobSchema.js";
import { User } from "./models/userSchema.js";
import { findFile, uploadFromPath } from "./utils/gridfs.js";

config({ path: ".env" });

const STUDENT_EMAIL = "student@jain.test";
const JOB_COMPANY = "PayPal";
const JOB_TITLE = "React Developer";

// Mid-range for that posting (₹12–18L), so it reads as a realistic offer
// rather than the top of the band.
const OFFER_CTC = 1450000;

const RESUME_FILENAME = "demo-student-resume.pdf";

const COVER_LETTER =
  "I am a final-year B.Tech Computer Science student at JAIN. I have built a " +
  "full-stack MERN placement portal and would like to apply for this role.";

/** The pipeline, oldest first, with the note recorded at each step. */
const PIPELINE = [
  ["Applied", null],
  ["Shortlisted", "Strong React fundamentals; shortlisted for interview."],
  ["Interview", "Technical round scheduled on campus."],
  ["Offered", "Offer extended."],
  ["Placed", "Offer accepted by candidate."],
];

/**
 * Build a small but genuinely valid one-page PDF.
 *
 * Written by hand rather than pulled from a fixture so the repository does not
 * carry a binary, and rather than faked with a stub so that clicking "Resume
 * sent" in the demo actually opens a readable document. Offsets in the xref
 * table are computed, which is what makes it valid rather than merely
 * PDF-shaped.
 */
const buildResumePdf = (student) => {
  const lines = [
    [student.name || "Demo Student", 22],
    ["B.Tech Computer Science  |  JAIN (Deemed-to-be University)", 11],
    [
      `Enrollment ${student.enrollment || "-"}   |  Batch ${student.batch || "-"}  |  CGPA ${student.cgpa ?? "-"}`,
      11,
    ],
    ["", 11],
    ["SKILLS", 13],
    ["React, JavaScript, Node.js, Express, MongoDB, Tailwind CSS", 11],
    ["", 11],
    ["PROJECTS", 13],
    ["JAIN Placement Portal - a MERN application with role-based", 11],
    ["access for students, recruiters and the placement office.", 11],
    ["JWT auth in httpOnly cookies, GridFS resume storage, and", 11],
    ["MongoDB aggregation for placement analytics.", 11],
    ["", 11],
    ["Sample document generated by seedDemoApplication.js.", 9],
  ];

  const esc = (s) =>
    s.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");

  let y = 780;
  let content = "";
  for (const [text, size] of lines) {
    if (text) content += `BT /F1 ${size} Tf 60 ${y} Td (${esc(text)}) Tj ET\n`;
    y -= size + 8;
  }

  const objs = [
    "<</Type/Catalog/Pages 2 0 R>>",
    "<</Type/Pages/Kids[3 0 R]/Count 1>>",
    "<</Type/Page/Parent 2 0 R/MediaBox[0 0 595 842]/Contents 4 0 R/Resources<</Font<</F1 5 0 R>>>>>>",
    `<</Length ${content.length}>>\nstream\n${content}endstream`,
    "<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>",
  ];

  let pdf = "%PDF-1.4\n";
  const offsets = [];
  objs.forEach((o, i) => {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${o}\nendobj\n`;
  });
  const xref = pdf.length;
  pdf += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n`;
  offsets.forEach((o) => {
    pdf += `${String(o).padStart(10, "0")} 00000 n \n`;
  });
  pdf += `trailer\n<</Size ${objs.length + 1}/Root 1 0 R>>\nstartxref\n${xref}\n%%EOF\n`;

  return Buffer.from(pdf, "latin1");
};

/** Upload the generated PDF into the GridFS bucket via a temp file. */
const uploadResume = async (student) => {
  const tmp = path.join(os.tmpdir(), `jain-demo-resume-${Date.now()}.pdf`);
  fs.writeFileSync(tmp, buildResumePdf(student));
  try {
    return await uploadFromPath(tmp, {
      filename: RESUME_FILENAME,
      contentType: "application/pdf",
    });
  } finally {
    fs.rmSync(tmp, { force: true });
  }
};

const run = async () => {
  await mongoose.connect(process.env.MONGO_URI, { dbName: "JAIN_PLACEMENT" });
  console.log(`Connected to ${mongoose.connection.db.databaseName}\n`);

  const student = await User.findOne({ email: STUDENT_EMAIL, role: "Student" });
  if (!student) {
    throw new Error(
      `Student ${STUDENT_EMAIL} not found. Run "npm run seed:accounts" first.`
    );
  }

  const job = await Job.findOne({ company: JOB_COMPANY, title: JOB_TITLE });
  if (!job) {
    throw new Error(
      `Job "${JOB_COMPANY} — ${JOB_TITLE}" not found. Run "npm run seed:jobs" first.`
    );
  }

  // Academic fields feed the branch-wise chart and the student directory. The
  // seeded student has none, and an "Unspecified" branch makes that chart look
  // broken rather than empty.
  let filledAcademics = false;
  if (!student.branch || !student.batch || student.cgpa == null) {
    student.branch = student.branch || "Computer Science";
    student.batch = student.batch || 2026;
    student.cgpa = student.cgpa ?? 8.7;
    await student.save();
    filledAcademics = true;
  }

  const existing = await Application.findOne({
    "applicantID.user": student._id,
    jobId: job._id,
  });

  // Reuse the stored file if it is still in the bucket; only upload when there
  // is nothing usable, so re-running does not leave orphaned GridFS entries.
  let resume = existing?.resume;
  let uploadedResume = false;
  if (!resume?.fileId || !(await findFile(resume.fileId))) {
    resume = await uploadResume(student);
    uploadedResume = true;
  }

  // Backdate the pipeline over the past three weeks so the tracker shows a
  // plausible progression instead of five identical timestamps.
  const now = Date.now();
  const DAY = 24 * 60 * 60 * 1000;
  const stamp = (i) => new Date(now - (PIPELINE.length - 1 - i) * 5 * DAY);
  const acceptedAt = stamp(PIPELINE.length - 1);
  const offeredAt = stamp(PIPELINE.length - 2);

  const doc =
    existing ||
    new Application({
      applicantID: { user: student._id, role: "Student" },
      jobId: job._id,
    });

  Object.assign(doc, {
    name: student.name,
    email: student.email,
    phone: student.phone,
    address: student.address,
    enrollment: student.enrollment,
    coverLetter: COVER_LETTER,
    recruiterId: { user: job.postedBy, role: "Recruiter" },
    resume,
    status: "Placed",
    statusHistory: PIPELINE.map(([status, note], i) => ({
      status,
      changedBy: i === 0 ? student._id : job.postedBy,
      changedAt: stamp(i),
      note: note ?? undefined,
    })),
    offer: {
      ctc: OFFER_CTC,
      role: job.title,
      offeredAt,
      acceptedAt,
    },
  });

  await doc.save();

  // Same denormalisation the status handler performs when an application
  // reaches Placed, so the student directory agrees with the analytics screen.
  student.placementStatus = "Placed";
  student.placedAt = { company: job.company, ctc: OFFER_CTC, placedOn: acceptedAt };
  await student.save();

  const inr = (n) => `Rs ${n.toLocaleString("en-IN")}`;
  console.log(`  ${existing ? "updated" : "created"}  application ${doc._id}`);
  console.log(`  student   ${student.name} <${student.email}>`);
  console.log(`  job       ${job.company} — ${job.title}`);
  console.log(`  status    Placed, offer ${inr(OFFER_CTC)}`);
  console.log(`  resume    ${resume.filename} (${resume.size} bytes)${uploadedResume ? " — uploaded" : " — reused"}`);
  if (filledAcademics) {
    console.log(`  academics filled: ${student.branch} / ${student.batch} / CGPA ${student.cgpa}`);
  }
  console.log(
    `\n  Placed applications now: ${await Application.countDocuments({ status: "Placed" })}`
  );

  await mongoose.disconnect();
};

run().catch((err) => {
  console.error("Demo application seed failed:", err.message);
  process.exit(1);
});
